const sunglassesDescriptions = {
    male: [
        "{{NAME}} mang phong cách mạnh mẽ và hiện đại, phù hợp với người đàn ông yêu sự tự do và cá tính. Thiết kế gọng chắc chắn giúp bảo vệ đôi mắt khi di chuyển ngoài trời. Một phụ kiện vừa thời trang vừa thực tế cho nhịp sống năng động.",
        "{{NAME}} thể hiện gu thẩm mỹ nam tính với những đường nét dứt khoát. Cảm giác đeo thoải mái giúp bạn tự tin sử dụng suốt cả ngày. Phù hợp từ di chuyển hàng ngày đến những chuyến đi xa.",
        "{{NAME}} mang tinh thần nam tính phóng khoáng và tự tin. Gọng kính chắc chắn giúp bảo vệ mắt khi di chuyển ngoài trời. Phù hợp cho nhịp sống năng động mỗi ngày.",
        "{{NAME}} thể hiện phong cách mạnh mẽ nhưng vẫn tinh tế. Thiết kế ôm gọn giúp tạo cảm giác thoải mái khi đeo lâu. Một phụ kiện không thể thiếu dưới nắng.",
        "{{NAME}} dành cho người đàn ông yêu sự chủ động và tự do. Gọng kính cứng cáp giúp đồng hành cùng nhiều hoạt động ngoài trời. Phong cách được khẳng định tự nhiên.",
        "{{NAME}} mang đến vẻ ngoài gọn gàng và nam tính. Thiết kế cân đối giúp kính phù hợp với nhiều khuôn mặt. Lựa chọn lý tưởng cho ngày nắng.",
        "{{NAME}} thể hiện gu thẩm mỹ hiện đại của nam giới. Cảm giác đeo dễ chịu giúp bạn sử dụng suốt cả ngày dài. Phù hợp từ công việc đến dạo phố.",
        "{{NAME}} mang phong cách khỏe khoắn và linh hoạt. Gọng kính chắc tay giúp tăng độ ổn định khi di chuyển. Một phụ kiện thực tế cho cuộc sống thường nhật.",
        "{{NAME}} phản ánh tinh thần năng động và tự tin. Thiết kế gọn nhẹ giúp kính không gây áp lực khi đeo lâu. Phù hợp cho nhiều hoàn cảnh khác nhau.",
        "{{NAME}} giúp hoàn thiện phong cách nam giới hiện đại. Gọng kính bền bỉ hỗ trợ bảo vệ mắt hiệu quả. Lựa chọn đáng tin cậy cho ngày nắng.",
        "{{NAME}} mang lại cảm giác chắc chắn và nam tính. Thiết kế hài hòa giúp kính dễ phối với trang phục. Phụ kiện đồng hành khi ra ngoài.",
        "{{NAME}} phù hợp với người đàn ông yêu sự tối giản nhưng mạnh mẽ. Gọng kính ôm vừa vặn giúp tăng trải nghiệm sử dụng. Phong cách thể hiện tinh tế.",
        "{{NAME}} mang phong thái tự tin và chủ động. Thiết kế cân đối giúp kính phù hợp nhiều hoạt động. Một lựa chọn linh hoạt cho ngày nắng.",
        "{{NAME}} thể hiện lối sống năng động của nam giới. Gọng kính chắc chắn giúp bạn an tâm khi sử dụng. Phụ kiện không thể thiếu khi ra ngoài.",
        "{{NAME}} mang đến vẻ ngoài gọn gàng và hiện đại. Thiết kế nhẹ giúp giảm cảm giác mỏi khi đeo lâu. Phù hợp cho cả di chuyển và nghỉ ngơi.",
        "{{NAME}} dành cho người đàn ông yêu sự thoải mái và tiện dụng. Gọng kính bền bỉ giúp bảo vệ mắt dưới ánh nắng. Phong cách thể hiện tự nhiên.",
        "{{NAME}} mang tinh thần phóng khoáng và linh hoạt. Thiết kế ôm gọn giúp kính ổn định khi vận động. Phù hợp cho nhịp sống năng động.",
        "{{NAME}} giúp hoàn thiện phong cách nam tính hàng ngày. Gọng kính chắc tay mang lại cảm giác an tâm. Phụ kiện thực tế cho cuộc sống hiện đại.",
        "{{NAME}} phản ánh gu thẩm mỹ nam giới hiện đại. Thiết kế hài hòa giúp kính dễ dàng sử dụng lâu dài. Phù hợp nhiều bối cảnh.",
        "{{NAME}} mang đến phong cách mạnh mẽ nhưng không phô trương. Gọng kính gọn nhẹ giúp đeo thoải mái cả ngày. Một lựa chọn linh hoạt.",
        "{{NAME}} phù hợp với người đàn ông yêu sự đơn giản và hiệu quả. Thiết kế chắc chắn giúp kính đồng hành cùng bạn. Phụ kiện đáng tin cậy.",
        "{{NAME}} mang lại cảm giác tự tin khi ra ngoài nắng. Gọng kính ổn định giúp tăng trải nghiệm sử dụng. Phong cách thể hiện rõ nét."

    ],
    female: [
        "{{NAME}} tôn lên vẻ thanh lịch và cuốn hút của người phụ nữ hiện đại. Thiết kế gọn nhẹ giúp dễ dàng phối cùng nhiều phong cách thời trang. Một điểm nhấn tinh tế cho những ngày nắng.",
        "{{NAME}} mang đến cảm giác thời trang nhưng không phô trương. Gọng kính ôm vừa vặn giúp bảo vệ mắt hiệu quả. Phù hợp cho cả công việc lẫn dạo phố.",
        "{{NAME}} tôn lên vẻ ngoài thanh lịch và hiện đại. Thiết kế gọng nhẹ giúp đeo thoải mái suốt ngày dài. Phụ kiện hoàn hảo cho những ngày nắng.",
        "{{NAME}} mang đến phong thái nữ tính và tinh tế. Gọng kính ôm vừa vặn giúp bảo vệ mắt hiệu quả. Dễ dàng phối cùng nhiều trang phục.",
        "{{NAME}} giúp hoàn thiện phong cách thời trang nhẹ nhàng. Thiết kế gọn gàng tạo cảm giác thoải mái khi đeo. Một điểm nhấn duyên dáng.",
        "{{NAME}} thể hiện vẻ đẹp hiện đại và tự tin. Gọng kính nhẹ giúp sử dụng lâu không gây khó chịu. Phù hợp cho dạo phố và công việc.",
        "{{NAME}} mang đến cảm giác thanh thoát và thời trang. Thiết kế hài hòa giúp kính phù hợp nhiều khuôn mặt. Phụ kiện dễ phối đồ.",
        "{{NAME}} dành cho người phụ nữ yêu sự tinh giản. Gọng kính ôm nhẹ giúp bảo vệ mắt khi ra nắng. Phong cách thể hiện tự nhiên.",
        "{{NAME}} giúp tôn lên nét nữ tính hiện đại. Thiết kế nhẹ nhàng mang lại cảm giác dễ chịu. Phù hợp cho nhiều hoạt động hàng ngày.",
        "{{NAME}} mang phong thái dịu dàng nhưng tự tin. Gọng kính cân đối giúp tạo sự thoải mái khi đeo. Một lựa chọn tinh tế.",
        "{{NAME}} thể hiện gu thẩm mỹ thanh lịch của phái đẹp. Thiết kế gọn nhẹ giúp kính không gây nặng mặt. Phụ kiện lý tưởng cho ngày nắng.",
        "{{NAME}} mang đến vẻ ngoài cuốn hút và hiện đại. Gọng kính ôm vừa giúp tăng trải nghiệm sử dụng. Dễ dàng phối nhiều phong cách.",
        "{{NAME}} phù hợp với người phụ nữ yêu sự tiện dụng. Thiết kế nhẹ giúp đeo lâu vẫn dễ chịu. Một điểm nhấn thời trang.",
        "{{NAME}} mang phong cách nữ tính nhưng linh hoạt. Gọng kính chắc chắn giúp bảo vệ mắt tốt hơn. Phù hợp cả đi làm lẫn dạo phố.",
        "{{NAME}} giúp hoàn thiện phong cách thời trang hàng ngày. Thiết kế hài hòa tạo cảm giác nhẹ nhàng. Phụ kiện dễ sử dụng.",
        "{{NAME}} mang đến sự tự tin trong từng bước di chuyển. Gọng kính nhẹ giúp đeo lâu không mỏi. Phù hợp cho cuộc sống năng động.",
        "{{NAME}} thể hiện vẻ đẹp tinh tế và hiện đại. Thiết kế gọn gàng giúp kính luôn dễ phối đồ. Một lựa chọn thanh lịch.",
        "{{NAME}} phù hợp với người phụ nữ yêu sự thoải mái. Gọng kính ôm nhẹ mang lại cảm giác dễ chịu. Phụ kiện cần thiết khi ra nắng.",
        "{{NAME}} mang phong thái trẻ trung và thời trang. Thiết kế nhẹ giúp kính không gây áp lực. Phù hợp cho nhiều dịp.",
        "{{NAME}} giúp tôn lên nét duyên dáng tự nhiên. Gọng kính cân đối giúp đeo ổn định. Phụ kiện tinh tế.",
        "{{NAME}} mang đến vẻ ngoài thanh lịch và năng động. Thiết kế gọn nhẹ giúp sử dụng hàng ngày. Dễ phối cùng trang phục.",
        "{{NAME}} thể hiện phong cách nữ tính hiện đại. Gọng kính nhẹ nhàng giúp bảo vệ mắt hiệu quả. Một lựa chọn tinh giản."

    ],
    unisex: [
        "{{NAME}} sở hữu thiết kế trung tính phù hợp với nhiều phong cách khác nhau. Gọng kính nhẹ giúp mang lại cảm giác dễ chịu khi sử dụng lâu. Một phụ kiện linh hoạt cho cuộc sống hiện đại.",
        "{{NAME}} kết hợp giữa thẩm mỹ tối giản và tính ứng dụng cao. Thiết kế hài hòa giúp dễ dàng sử dụng hàng ngày. Phù hợp cho cả nam và nữ.",
        "{{NAME}} sở hữu thiết kế trung tính dễ tiếp cận. Gọng kính nhẹ giúp đeo thoải mái cả ngày. Phù hợp cho nhiều phong cách.",
        "{{NAME}} mang phong cách tối giản và hiện đại. Thiết kế hài hòa giúp kính dễ sử dụng hàng ngày. Phụ kiện linh hoạt.",
        "{{NAME}} phù hợp cho cả nam và nữ yêu sự tiện dụng. Gọng kính gọn nhẹ mang lại cảm giác dễ chịu. Một lựa chọn thực tế.",
        "{{NAME}} thể hiện tinh thần trẻ trung và năng động. Thiết kế trung tính giúp kính dễ phối đồ. Phù hợp nhiều hoàn cảnh.",
        "{{NAME}} mang đến cảm giác thoải mái khi sử dụng lâu. Gọng kính nhẹ giúp giảm áp lực khi đeo. Phụ kiện hàng ngày.",
        "{{NAME}} kết hợp giữa thẩm mỹ và tính ứng dụng. Thiết kế đơn giản giúp kính không lỗi mốt. Phù hợp cho mọi giới.",
        "{{NAME}} mang phong cách linh hoạt và hiện đại. Gọng kính cân đối giúp đeo ổn định. Dễ dàng sử dụng.",
        "{{NAME}} phù hợp với lối sống năng động. Thiết kế gọn nhẹ giúp kính đồng hành cả ngày. Phụ kiện tiện lợi.",
        "{{NAME}} thể hiện gu thẩm mỹ tối giản. Gọng kính nhẹ giúp tăng trải nghiệm sử dụng. Phù hợp nhiều đối tượng.",
        "{{NAME}} mang đến vẻ ngoài hiện đại và dễ tiếp cận. Thiết kế trung tính giúp kính phù hợp mọi phong cách. Lựa chọn linh hoạt.",
        "{{NAME}} phù hợp cho cả đi làm và dạo phố. Gọng kính nhẹ giúp đeo lâu không khó chịu. Phụ kiện tiện dụng.",
        "{{NAME}} mang tinh thần trẻ trung và thoải mái. Thiết kế cân đối giúp kính ổn định khi đeo. Phù hợp hàng ngày.",
        "{{NAME}} thể hiện phong cách sống tối giản. Gọng kính gọn gàng giúp dễ sử dụng lâu dài. Phụ kiện linh hoạt.",
        "{{NAME}} mang đến cảm giác nhẹ nhàng khi đeo. Thiết kế trung tính phù hợp nhiều khuôn mặt. Lựa chọn tiện lợi.",
        "{{NAME}} phù hợp cho người yêu sự đơn giản. Gọng kính nhẹ giúp đeo dễ chịu cả ngày. Phụ kiện dễ dùng.",
        "{{NAME}} mang phong cách hiện đại và trung tính. Thiết kế hài hòa giúp kính dễ phối đồ. Phù hợp cho mọi giới.",
        "{{NAME}} thể hiện sự linh hoạt trong phong cách. Gọng kính nhẹ giúp sử dụng thường xuyên. Phụ kiện thực tế.",
        "{{NAME}} mang đến trải nghiệm đeo thoải mái. Thiết kế đơn giản giúp kính không bị lỗi thời. Phù hợp hàng ngày.",
        "{{NAME}} phù hợp với nhiều độ tuổi và phong cách. Gọng kính cân đối giúp đeo ổn định. Một lựa chọn an toàn.",
        "{{NAME}} mang phong thái tối giản và hiện đại. Thiết kế nhẹ giúp kính dễ sử dụng lâu dài. Phụ kiện linh hoạt."

    ]
};


